import type { Template } from './types';
import { CheckCircle2, Star, Zap, Circle, Square, ChevronRight, Triangle, Hexagon, Diamond, Grid3X3 } from 'lucide-react';
import React from 'react';
import type { Slide, SlideLayout } from './types';

// Helper function to convert hex to RGB
function hexToRgb(hex: string): string {
  // Remove # if present
  hex = hex.replace(/^#/, '');
  
  // Parse the hex values
  const bigint = parseInt(hex, 16);
  const r = (bigint >> 16) & 255;
  const g = (bigint >> 8) & 255;
  const b = bigint & 255;
  
  return `${r}, ${g}, ${b}`;
}
// Helper function to create a lighter version of a hex color
function lightenColor(hex: string, percent = 30): string {
  // Remove # if present
  hex = hex.replace(/^#/, '');
  
  // Parse the hex values
  const r = parseInt(hex.substring(0, 2), 16);
  const g = parseInt(hex.substring(2, 4), 16);
  const b = parseInt(hex.substring(4, 6), 16);
  
  // Lighten
  const newR = Math.min(255, Math.floor(r + (255 - r) * percent / 100));
  const newG = Math.min(255, Math.floor(g + (255 - g) * percent / 100));
  const newB = Math.min(255, Math.floor(b + (255 - b) * percent / 100));
  
  // Convert back to hex
  return `#${newR.toString(16).padStart(2, '0')}${newG.toString(16).padStart(2, '0')}${newB.toString(16).padStart(2, '0')}`;
}
// Helper function to create a darker version of a hex color
function darkenColor(hex: string, percent = 15): string {
  // Remove # if present
  hex = hex.replace(/^#/, '');
  
  // Parse the hex values
  const r = parseInt(hex.substring(0, 2), 16);
  const g = parseInt(hex.substring(2, 4), 16);
  const b = parseInt(hex.substring(4, 6), 16);
  
  // Darken
  const newR = Math.max(0, Math.floor(r - r * percent / 100));
  const newG = Math.max(0, Math.floor(g - g * percent / 100));
  const newB = Math.max(0, Math.floor(b - b * percent / 100));
  
  // Convert back to hex
  return `#${newR.toString(16).padStart(2, '0')}${newG.toString(16).padStart(2, '0')}${newB.toString(16).padStart(2, '0')}`;
}
// We define the actual components in SlideView and just reference their names here.
// This avoids circular dependencies and keeps this as a data/configuration file.
const FallbackComponent = ({ slide }: { slide: any }) => (
  <div className="w-full h-full flex flex-col items-center justify-center bg-red-100 text-red-800 p-8">
    <h2 className="text-2xl font-bold mb-4">Layout Not Found</h2>
    <p>No design available for layout type: <strong>{slide.layout}</strong></p>
  </div>
);
const TitleLayout = (props: any) => <div />;
const ContentLayout = (props: any) => <div />;
const genericDesigns: Record<SlideLayout, React.FC<any>> = {
    'title': TitleLayout,
    'content': ContentLayout,
    'two-column': ContentLayout,
    'two-column-headed': ContentLayout,
    'three-column': ContentLayout,
    'three-column-headed': ContentLayout,
    'four-column': ContentLayout,
    'image-right': ContentLayout,
    'image-left': ContentLayout,
    'title-bullets': ContentLayout,
    'title-bullets-image': ContentLayout,
    'quote': ContentLayout,
    'blank': (props: any) => <div/>,
    'comparison': ContentLayout,
    'code': ContentLayout,
    'accent-left': ContentLayout,
    'accent-right': ContentLayout,
    'accent-top': ContentLayout,
    'accent-right-fit': ContentLayout,
    'accent-left-fit': ContentLayout,
    'accent-background': ContentLayout,
    'two-image-columns': ContentLayout,
    'three-image-columns': ContentLayout,
    'four-image-columns': ContentLayout,
    'images-with-text': ContentLayout,
    'image-gallery': ContentLayout,
    'team-photos': ContentLayout,
    'data-chart': ContentLayout,
    'timeline': ContentLayout,
    'process-flow': ContentLayout,
    'section-header': ContentLayout,
};
export const templates: Template[] = [
  // Light Themes
  {
    id: 'light-1',
    name: 'Modern Corp',
    theme: 'light',
    category: 'standard',
    colors: {
      background: '#F8F9FA',
      cardBackground: '#FFFFFF',
      cardBorder: '#DEE2E6',
      cardShadow: 'rgba(108, 117, 125, 0.15)',
      text: '#212529',
      heading: '#0D1B2A',
      primary: '#005F73',
      accent: '#D9534F',
      primaryLight: lightenColor('#005F73', 30),
      accentLight: lightenColor('#D9534F', 30),
      primaryRgb: hexToRgb('#005F73'),
      accentRgb: hexToRgb('#D9534F'),
    },
    font: {
      headline: "'Playfair Display', serif",
      body: "'Lato', sans-serif",
    },
    background: '#F8F9FA',
    icons: {
      bullet: Circle
    },
    designs: genericDesigns,
  },
  {
    id: 'light-2',
    name: 'Creative',
    theme: 'light',
    category: 'standard',
    colors: {
      background: '#FFFBF5',
      cardBackground: '#FFFFFF',
      cardBorder: '#F7EFE5',
      cardShadow: 'rgba(120, 100, 80, 0.1)',
      text: '#1E3D59',
      heading: '#4E6E81',
      primary: '#FF6B6B',
      accent: '#48BFE3',
      primaryLight: lightenColor('#FF6B6B', 30),
      accentLight: lightenColor('#48BFE3', 30),
      primaryRgb: hexToRgb('#FF6B6B'),
      accentRgb: hexToRgb('#48BFE3'),
    },
    font: {
      headline: "'Playfair Display', serif",
      body: "'Montserrat', sans-serif",
    },
    background: '#FFFBF5',
    icons: {
      bullet: Star
    },
    designs: genericDesigns,
  },
  {
    id: 'light-3',
    name: 'Minimal',
    theme: 'light',
    category: 'standard',
    colors: {
      background: '#F9FAFB',
      cardBackground: '#FFFFFF',
      cardBorder: '#F3F4F6',
      cardShadow: 'rgba(0, 0, 0, 0.06)',
      text: '#111827',
      heading: '#6B7280',
      primary: '#1F2937',
      accent: '#4F46E5',
      primaryLight: lightenColor('#1F2937', 30),
      accentLight: lightenColor('#4F46E5', 30),
      primaryRgb: hexToRgb('#1F2937'),
      accentRgb: hexToRgb('#4F46E5'),
    },
    font: {
      headline: "'Inter', sans-serif",
      body: "'Inter', sans-serif",
    },
    background: '#F9FAFB',
    icons: {
      bullet: ChevronRight
    },
    designs: genericDesigns,
  },
  {
    id: 'light-4',
    name: 'Vibrant',
    theme: 'light',
    category: 'standard',
    colors: {
      background: '#FFFFFF',
      cardBackground: '#F7F7F7',
      cardBorder: '#EDEDED',
      cardShadow: 'rgba(0, 0, 0, 0.09)',
      text: '#2E4057',
      heading: '#637081',
      primary: '#00A896',
      accent: '#F0C808',
      primaryLight: lightenColor('#00A896', 30),
      accentLight: lightenColor('#F0C808', 30),
      primaryRgb: hexToRgb('#00A896'),
      accentRgb: hexToRgb('#F0C808'),
    },
    font: {
      headline: "'Poppins', sans-serif",
      body: "'Nunito Sans', sans-serif",
    },
    background: '#FFFFFF',
    icons: {
      bullet: Square
    },
    designs: genericDesigns,
  },
  {
    id: 'light-5',
    name: 'Meadow',
    theme: 'light',
    category: 'standard',
    colors: {
        background: '#F4F4F2',
        cardBackground: '#FFFFFF',
        cardBorder: '#E8E8E3',
        cardShadow: 'rgba(74, 78, 105, 0.1)',
        text: '#22223B',
        heading: '#4A4E69',
        primary: '#6A994E',
        accent: '#BC4749',
        primaryLight: lightenColor('#6A994E', 30),
        accentLight: lightenColor('#BC4749', 30),
        primaryRgb: hexToRgb('#6A994E'),
        accentRgb: hexToRgb('#BC4749'),
    },
    font: {
        headline: "'Domine', serif",
        body: "'Open Sans', sans-serif",
    },
    background: '#F4F4F2',
    designs: genericDesigns,
  },
  {
    id: 'light-6',
    name: 'Sunrise',
    theme: 'light',
    category: 'standard',
    colors: {
        background: '#FFF9E9',
        cardBackground: '#FFFFFF',
        cardBorder: '#FFEECF',
        cardShadow: 'rgba(246, 174, 45, 0.15)',
        text: '#0A2342',
        heading: '#2E4057',
        primary: '#33658A',
        accent: '#F26419',
        primaryLight: lightenColor('#33658A', 30),
        accentLight: lightenColor('#F26419', 30),
        primaryRgb: hexToRgb('#33658A'),
        accentRgb: hexToRgb('#F26419'),
    },
    font: {
        headline: "'Arvo', serif",
        body: "'Cabin', sans-serif",
    },
    background: '#FFF9E9',
    designs: genericDesigns,
  },
   {
    id: 'light-7',
    name: 'Ocean',
    theme: 'light',
    category: 'standard',
    colors: {
        background: '#F0F9FF',
        cardBackground: '#FFFFFF',
        cardBorder: '#E0F2FE',
        cardShadow: 'rgba(56, 189, 248, 0.1)',
        text: '#1F2937',
        heading: '#4B5563',
        primary: '#0284C7',
        accent: '#F97316',
        primaryLight: lightenColor('#0284C7', 30),
        accentLight: lightenColor('#F97316', 30),
        primaryRgb: hexToRgb('#0284C7'),
        accentRgb: hexToRgb('#F97316'),
    },
    font: {
        headline: "'Patua One', cursive",
        body: "'Source Sans Pro', sans-serif",
    },
    background: '#F0F9FF',
    designs: genericDesigns,
  },
   {
    id: 'light-8',
    name: 'Sakura',
    theme: 'light',
    category: 'standard',
    colors: {
        background: '#FEF6F6',
        cardBackground: '#FFFFFF',
        cardBorder: '#FEECEC',
        cardShadow: 'rgba(231, 111, 81, 0.1)',
        text: '#264653',
        heading: '#6B705C',
        primary: '#2A9D8F',
        accent: '#E76F51',
        primaryLight: lightenColor('#2A9D8F', 30),
        accentLight: lightenColor('#E76F51', 30),
        primaryRgb: hexToRgb('#2A9D8F'),
        accentRgb: hexToRgb('#E76F51'),
    },
    font: {
        headline: "'Zilla Slab', serif",
        body: "'Hind', sans-serif",
    },
    background: '#FEF6F6',
    designs: genericDesigns,
  },
  {
    id: 'light-9',
    name: 'Slate',
    theme: 'light',
    category: 'standard',
    colors: {
        background: '#F8F9FA',
        cardBackground: '#FFFFFF',
        cardBorder: '#DEE2E6',
        cardShadow: 'rgba(108, 117, 125, 0.1)',
        text: '#0B2545',
        heading: '#3E5C76',
        primary: '#1D3557',
        accent: '#E63946',
        primaryLight: lightenColor('#1D3557', 30),
        accentLight: lightenColor('#E63946', 30),
        primaryRgb: hexToRgb('#1D3557'),
        accentRgb: hexToRgb('#E63946'),
    },
    font: {
        headline: "'Work Sans', sans-serif",
        body: "'Work Sans', sans-serif",
    },
    background: '#F8F9FA',
    designs: genericDesigns,
  },
   {
    id: 'light-10',
    name: 'Peach',
    theme: 'light',
    category: 'standard',
    colors: {
        background: '#FFF5EB',
        cardBackground: '#FFFFFF',
        cardBorder: '#FFE8D1',
        cardShadow: 'rgba(252, 163, 17, 0.1)',
        text: '#14213D',
        heading: '#6C757D',
        primary: '#118AB2',
        accent: '#06D6A0',
        primaryLight: lightenColor('#118AB2', 30),
        accentLight: lightenColor('#06D6A0', 30),
        primaryRgb: hexToRgb('#118AB2'),
        accentRgb: hexToRgb('#06D6A0'),
    },
    font: {
        headline: "'Cormorant Garamond', serif",
        body: "'Proza Libre', sans-serif",
    },
    background: '#FFF5EB',
    designs: genericDesigns,
  },
  {
    id: 'light-11',
    name: 'Academic',
    theme: 'light',
    category: 'standard',
    colors: {
        background: '#FDFCFB',
        cardBackground: '#FFFFFF',
        cardBorder: '#F3EFEA',
        cardShadow: 'rgba(58, 58, 58, 0.1)',
        text: '#3A3A3A',
        heading: '#5F6368',
        primary: '#0B7285',
        accent: '#D9480F',
        primaryLight: lightenColor('#0B7285', 30),
        accentLight: lightenColor('#D9480F', 30),
        primaryRgb: hexToRgb('#0B7285'),
        accentRgb: hexToRgb('#D9480F'),
    },
    font: {
        headline: "'Lora', serif",
        body: "'Georgia', serif",
    },
    background: '#FDFCFB',
    designs: genericDesigns,
  },
   {
    id: 'light-12',
    name: 'Retro',
    theme: 'light',
    category: 'standard',
    colors: {
        background: '#FAF3E0',
        cardBackground: '#FFFFFF',
        cardBorder: '#EFE6D8',
        cardShadow: 'rgba(44, 62, 80, 0.12)',
        text: '#2C3E50',
        heading: '#7F8C8D',
        primary: '#2980B9',
        accent: '#E67E22',
        primaryLight: lightenColor('#2980B9', 30),
        accentLight: lightenColor('#E67E22', 30),
        primaryRgb: hexToRgb('#2980B9'),
        accentRgb: hexToRgb('#E67E22'),
    },
    font: {
        headline: "'Righteous', cursive",
        body: "'Maven Pro', sans-serif",
    },
    background: '#FAF3E0',
    designs: genericDesigns,
  },
  {
    id: 'light-13',
    name: 'Spring',
    theme: 'light',
    category: 'standard',
    colors: {
        background: '#F0F7F4',
        cardBackground: '#FFFFFF',
        cardBorder: '#E1EBE6',
        cardShadow: 'rgba(0, 119, 182, 0.1)',
        text: '#1A1A1A',
        heading: '#555555',
        primary: '#0077B6',
        accent: '#90BE6D',
        primaryLight: lightenColor('#0077B6', 30),
        accentLight: lightenColor('#90BE6D', 30),
        primaryRgb: hexToRgb('#0077B6'),
        accentRgb: hexToRgb('#90BE6D'),
    },
    font: {
        headline: "'Quattrocento', serif",
        body: "'Quattrocento Sans', sans-serif",
    },
    background: '#F0F7F4',
    designs: genericDesigns,
  },
  {
    id: 'light-14',
    name: 'Lavender',
    theme: 'light',
    category: 'standard',
    colors: {
        background: '#F5F3FF',
        cardBackground: '#FFFFFF',
        cardBorder: '#EDE9FE',
        cardShadow: 'rgba(99, 102, 241, 0.1)',
        text: '#111827',
        heading: '#6B7280',
        primary: '#6366F1',
        accent: '#F59E0B',
        primaryLight: lightenColor('#6366F1', 30),
        accentLight: lightenColor('#F59E0B', 30),
        primaryRgb: hexToRgb('#6366F1'),
        accentRgb: hexToRgb('#F59E0B'),
    },
    font: {
        headline: "'DM Serif Display', serif",
        body: "'DM Sans', sans-serif",
    },
    background: '#F5F3FF',
    designs: genericDesigns,
  },
  {
    id: 'light-15',
    name: 'Sandstone',
    theme: 'light',
    category: 'standard',
    colors: {
        background: '#F9F9F9',
        cardBackground: '#FFFFFF',
        cardBorder: '#F0F0F0',
        cardShadow: 'rgba(0, 0, 0, 0.08)',
        text: '#1F2937',
        heading: '#4B5563',
        primary: '#EF4444',
        accent: '#10B981',
        primaryLight: lightenColor('#EF4444', 30),
        accentLight: lightenColor('#10B981', 30),
        primaryRgb: hexToRgb('#EF4444'),
        accentRgb: hexToRgb('#10B981'),
    },
    font: {
        headline: "'Teko', sans-serif",
        body: "'Exo 2', sans-serif",
    },
    background: '#F9F9F9',
    designs: genericDesigns,
  },
  // Dark Themes
  {
    id: 'dark-1',
    name: 'Galaxy',
    theme: 'dark',
    category: 'standard',
    colors: {
      background: '#121212',
      cardBackground: '#1E1E1E',
      cardBorder: '#2C2C2C',
      cardShadow: 'rgba(0, 0, 0, 0.5)',
      text: '#E0E0E0',
      heading: '#B0BEC5',
      primary: '#FFA726',
      accent: '#26C6DA',
      primaryLight: lightenColor('#FFA726', 30),
      accentLight: lightenColor('#26C6DA', 30),
      primaryRgb: hexToRgb('#FFA726'),
      accentRgb: hexToRgb('#26C6DA'),
    },
    font: {
      headline: "'Space Grotesk', sans-serif",
      body: "'Inter', sans-serif",
    },
    background: '#121212',
    designs: genericDesigns,
  },
  {
    id: 'dark-2',
    name: 'Nebula',
    theme: 'dark',
    category: 'standard',
    colors: {
      background: '#0F0C29',
      cardBackground: '#1D1939',
      cardBorder: '#2C2650',
      cardShadow: 'rgba(0, 0, 0, 0.5)',
      text: '#ECEFF1',
      heading: '#90A4AE',
      primary: '#FFC107',
      accent: '#00F5D4',
      primaryLight: lightenColor('#FFC107', 30),
      accentLight: lightenColor('#00F5D4', 30),
      primaryRgb: hexToRgb('#FFC107'),
      accentRgb: hexToRgb('#00F5D4'),
    },
    font: {
      headline: "'Orbitron', sans-serif",
      body: "'Titillium Web', sans-serif",
    },
    background: '#0F0C29',
    designs: genericDesigns,
  },
  {
    id: 'dark-3',
    name: 'Forest',
    theme: 'dark',
    category: 'standard',
    colors: {
      background: '#0C1821',
      cardBackground: '#1B2A32',
      cardBorder: '#2A3C44',
      cardShadow: 'rgba(0, 0, 0, 0.5)',
      text: '#E0E1DD',
      heading: '#778DA9',
      primary: '#FCA311',
      accent: '#83C5BE',
      primaryLight: lightenColor('#FCA311', 30),
      accentLight: lightenColor('#83C5BE', 30),
      primaryRgb: hexToRgb('#FCA311'),
      accentRgb: hexToRgb('#83C5BE'),
    },
    font: {
      headline: "'Merriweather', serif",
      body: "'Lato', sans-serif",
    },
    background: '#0C1821',
    designs: genericDesigns,
  },
  {
    id: 'dark-4',
    name: 'Console',
    theme: 'dark',
    category: 'standard',
    colors: {
      background: '#121212',
      cardBackground: '#1E1E1E',
      cardBorder: '#2F2F2F',
      cardShadow: 'rgba(0, 0, 0, 0.6)',
      text: '#DADDD8',
      heading: '#A9A9A9',
      primary: '#39FF14',
      accent: '#F92672',
      primaryLight: lightenColor('#39FF14', 30),
      accentLight: lightenColor('#F92672', 30),
      primaryRgb: hexToRgb('#39FF14'),
      accentRgb: hexToRgb('#F92672'),
    },
    font: {
      headline: "'Source Code Pro', monospace",
      body: "'Fira Code', monospace",
    },
    background: '#121212',
    designs: genericDesigns,
  },
   {
    id: 'dark-5',
    name: 'Ember',
    theme: 'dark',
    category: 'standard',
    colors: {
        background: '#1C1C1C',
        cardBackground: '#2A2A2A',
        cardBorder: '#383838',
        cardShadow: 'rgba(255, 115, 76, 0.1)',
        text: '#F1F1F1',
        heading: '#9E9E9E',
        primary: '#FFC857',
        accent: '#E9724C',
        primaryLight: lightenColor('#FFC857', 30),
        accentLight: lightenColor('#E9724C', 30),
        primaryRgb: hexToRgb('#FFC857'),
        accentRgb: hexToRgb('#E9724C'),
    },
    font: {
        headline: "'Oswald', sans-serif",
        body: "'Roboto Slab', serif",
    },
    background: '#1C1C1C',
    designs: genericDesigns,
  },
  {
    id: 'dark-6',
    name: 'Midnight',
    theme: 'dark',
    category: 'standard',
    colors: {
        background: '#0B0C10',
        cardBackground: '#1F2833',
        cardBorder: '#2C3A47',
        cardShadow: 'rgba(102, 252, 241, 0.1)',
        text: '#C5C6C7',
        heading: '#66FCF1',
        primary: '#45A29E',
        accent: '#ED254E',
        primaryLight: lightenColor('#45A29E', 30),
        accentLight: lightenColor('#ED254E', 30),
        primaryRgb: hexToRgb('#45A29E'),
        accentRgb: hexToRgb('#ED254E'),
    },
    font: {
        headline: "'Fjalla One', sans-serif",
        body: "'Nunito', sans-serif",
    },
    background: '#0B0C10',
    designs: genericDesigns,
  },
  {
    id: 'dark-7',
    name: 'Synthwave',
    theme: 'dark',
    category: 'standard',
    colors: {
        background: '#1A1A2E',
        cardBackground: '#252545',
        cardBorder: '#323261',
        cardShadow: 'rgba(249, 38, 114, 0.2)',
        text: '#E6E6E6',
        heading: '#AAAAAA',
        primary: '#00F5D4',
        accent: '#F92672',
        primaryLight: lightenColor('#00F5D4', 30),
        accentLight: lightenColor('#F92672', 30),
        primaryRgb: hexToRgb('#00F5D4'),
        accentRgb: hexToRgb('#F92672'),
    },
    font: {
        headline: "'Vast Shadow', cursive",
        body: "'Electrolize', sans-serif",
    },
    background: '#1A1A2E',
    designs: genericDesigns,
  },
   {
    id: 'dark-8',
    name: 'Abyss',
    theme: 'dark',
    category: 'standard',
    colors: {
        background: '#101820',
        cardBackground: '#1A222C',
        cardBorder: '#242F3A',
        cardShadow: 'rgba(254, 231, 21, 0.1)',
        text: '#FEE715',
        heading: '#BBBBBB',
        primary: '#F18805',
        accent: '#D72638',
        primaryLight: lightenColor('#F18805', 30),
        accentLight: lightenColor('#D72638', 30),
        primaryRgb: hexToRgb('#F18805'),
        accentRgb: hexToRgb('#D72638'),
    },
    font: {
        headline: "'Cinzel', serif",
        body: "'Fauna One', serif",
    },
    background: '#101820',
    designs: genericDesigns,
  },
   {
    id: 'dark-9',
    name: 'Executive',
    theme: 'dark',
    category: 'standard',
    colors: {
        background: '#181818',
        cardBackground: '#242424',
        cardBorder: '#333333',
        cardShadow: 'rgba(0, 0, 0, 0.5)',
        text: '#E0E0E0',
        heading: '#A0A0A0',
        primary: '#F05454',
        accent: '#30475E',
        primaryLight: lightenColor('#F05454', 30),
        accentLight: lightenColor('#30475E', 30),
        primaryRgb: hexToRgb('#F05454'),
        accentRgb: hexToRgb('#30475E'),
    },
    font: {
        headline: "'EB Garamond', serif",
        body: "'PT Serif', serif",
    },
    background: '#181818',
    designs: genericDesigns,
  },
  {
    id: 'dark-10',
    name: 'Gothic',
    theme: 'dark',
    category: 'standard',
    colors: {
        background: '#141414',
        cardBackground: '#1F1F1F',
        cardBorder: '#2A2A2A',
        cardShadow: 'rgba(0, 0, 0, 0.6)',
        text: '#FAFAFA',
        heading: '#9CA3AF',
        primary: '#F59E0B',
        accent: '#B91C1C',
        primaryLight: lightenColor('#F59E0B', 30),
        accentLight: lightenColor('#B91C1C', 30),
        primaryRgb: hexToRgb('#F59E0B'),
        accentRgb: hexToRgb('#B91C1C'),
    },
    font: {
        headline: "'UnifrakturMaguntia', cursive",
        body: "'Old Standard TT', serif",
    },
    background: '#141414',
    designs: genericDesigns,
  },
  {
    id: 'dark-11',
    name: 'Cyberpunk',
    theme: 'dark',
    category: 'standard',
    colors: {
        background: '#0F0F0F',
        cardBackground: '#1A1A1A',
        cardBorder: '#2A2A2A',
        cardShadow: 'rgba(59, 130, 246, 0.2)',
        text: '#D1D5DB',
        heading: '#9CA3AF',
        primary: '#EF4444',
        accent: '#3B82F6',
        primaryLight: lightenColor('#EF4444', 30),
        accentLight: lightenColor('#3B82F6', 30),
        primaryRgb: hexToRgb('#EF4444'),
        accentRgb: hexToRgb('#3B82F6'),
    },
    font: {
        headline: "'Bungee', cursive",
        body: "'Gruppo', sans-serif",
    },
    background: '#0F0F0F',
    designs: genericDesigns,
  },
   {
    id: 'dark-12',
    name: 'Bloodmoon',
    theme: 'dark',
    category: 'standard',
    colors: {
        background: '#1A1A1D',
        cardBackground: '#252528',
        cardBorder: '#353539',
        cardShadow: 'rgba(244, 162, 97, 0.15)',
        text: '#F7F7F7',
        heading: '#C0C0C0',
        primary: '#F4A261',
        accent: '#9B2226',
        primaryLight: lightenColor('#F4A261', 30),
        accentLight: lightenColor('#9B2226', 30),
        primaryRgb: hexToRgb('#F4A261'),
        accentRgb: hexToRgb('#9B2226'),
    },
    font: {
        headline: "'Creepster', cursive",
        body: "'IM Fell English', serif",
    },
    background: '#1A1A1D',
    designs: genericDesigns,
  },
  {
    id: 'dark-13',
    name: 'Oceanic',
    theme: 'dark',
    category: 'standard',
    colors: {
        background: '#03071E',
        cardBackground: '#0F142A',
        cardBorder: '#1C223C',
        cardShadow: 'rgba(187, 134, 252, 0.1)',
        text: '#E5E5E5',
        heading: '#999999',
        primary: '#D4AF37',
        accent: '#BB86FC',
        primaryLight: lightenColor('#D4AF37', 30),
        accentLight: lightenColor('#BB86FC', 30),
        primaryRgb: hexToRgb('#D4AF37'),
        accentRgb: hexToRgb('#BB86FC'),
    },
    font: {
        headline: "'Philosopher', sans-serif",
        body: "'Jost', sans-serif",
    },
    background: '#03071E',
    designs: genericDesigns,
  },
   {
    id: 'dark-14',
    name: 'Matrix',
    theme: 'dark',
    category: 'standard',
    colors: {
        background: '#000000',
        cardBackground: '#0D0D0D',
        cardBorder: '#1A1A1A',
        cardShadow: 'rgba(0, 255, 0, 0.2)',
        text: '#00FF00',
        heading: '#3CFF3C',
        primary: '#00FF00',
        accent: '#505050',
        primaryLight: lightenColor('#00FF00', 30),
        accentLight: lightenColor('#505050', 30),
        primaryRgb: hexToRgb('#00FF00'),
        accentRgb: hexToRgb('#505050'),
    },
    font: {
        headline: "'VT323', monospace",
        body: "'VT323', monospace",
    },
    background: '#000000',
    designs: genericDesigns,
  },
  {
    id: 'dark-15',
    name: 'Royal Gold',
    theme: 'dark',
    category: 'standard',
    colors: {
        background: '#202124',
        cardBackground: '#2D2F33',
        cardBorder: '#3A3C41',
        cardShadow: 'rgba(251, 133, 0, 0.15)',
        text: '#FFFFFF',
        heading: '#BDC1C6',
        primary: '#FB8500',
        accent: '#219EBC',
        primaryLight: lightenColor('#FB8500', 30),
        accentLight: lightenColor('#219EBC', 30),
        primaryRgb: hexToRgb('#FB8500'),
        accentRgb: hexToRgb('#219EBC'),
    },
    font: {
        headline: "'Cinzel Decorative', cursive",
        body: "'Antic Slab', serif",
    },
    background: '#202124',
    designs: genericDesigns,
  },
  // Gradient Themes
  {
    id: 'gradient-1',
    name: 'Pastel Dreams',
    theme: 'light',
    category: 'gradient',
    colors: {
        background: '#FFDEE9', 
        cardBackground: 'rgba(255, 255, 255, 0.8)',
        cardBorder: 'rgba(255, 255, 255, 0.5)',
        cardShadow: 'rgba(100, 100, 100, 0.1)',
        text: '#0D1B2A', 
        heading: '#415A77', 
        primary: '#1B263B', 
        accent: '#E63946',
        primaryLight: lightenColor('#1B263B', 30),
        accentLight: lightenColor('#E63946', 30),
        primaryRgb: hexToRgb('#1B263B'),
        accentRgb: hexToRgb('#E63946'),
    },
    font: { headline: "'Poppins', sans-serif", body: "'Inter', sans-serif" },
    background: 'linear-gradient(to right, #FFDEE9, #B5FFFC)',
    designs: genericDesigns,
  },
  {
    id: 'gradient-2',
    name: 'Cool Blue',
    theme: 'light',
    category: 'gradient',
    colors: {
        background: '#89F7FE', 
        cardBackground: 'rgba(255, 255, 255, 0.7)',
        cardBorder: 'rgba(255, 255, 255, 0.4)',
        cardShadow: 'rgba(102, 166, 255, 0.2)',
        text: '#1E3D59', 
        heading: '#003E5C', 
        primary: '#FF6E40', 
        accent: '#3D5A80',
        primaryLight: lightenColor('#FF6E40', 30),
        accentLight: lightenColor('#3D5A80', 30),
        primaryRgb: hexToRgb('#FF6E40'),
        accentRgb: hexToRgb('#3D5A80'),
    },
    font: { headline: "'Merriweather', serif", body: "'Lato', sans-serif" },
    background: 'linear-gradient(to right, #89F7FE, #66A6FF)',
    designs: genericDesigns,
  },
  {
    id: 'gradient-3',
    name: 'Sunny Days',
    theme: 'light',
    category: 'gradient',
    colors: {
        background: '#FDC830', 
        cardBackground: 'rgba(255, 255, 255, 0.85)',
        cardBorder: 'rgba(255, 255, 255, 0.6)',
        cardShadow: 'rgba(243, 115, 53, 0.2)',
        text: '#0F3460', 
        heading: '#6B728E', 
        primary: '#16213E', 
        accent: '#FF595E',
        primaryLight: lightenColor('#16213E', 30),
        accentLight: lightenColor('#FF595E', 30),
        primaryRgb: hexToRgb('#16213E'),
        accentRgb: hexToRgb('#FF595E'),
    },
    font: { headline: "'Patua One', cursive", body: "'Source Sans Pro', sans-serif" },
    background: 'linear-gradient(to right, #FDC830, #F37335)',
    designs: genericDesigns,
  },
  {
    id: 'gradient-4',
    name: 'Gentle Sky',
    theme: 'light',
    category: 'gradient',
    colors: {
        background: '#A1C4FD', 
        cardBackground: 'rgba(255, 255, 255, 0.9)',
        cardBorder: 'rgba(255, 255, 255, 0.7)',
        cardShadow: 'rgba(194, 233, 251, 0.4)',
        text: '#2E4057', 
        heading: '#637081', 
        primary: '#1F7A8C', 
        accent: '#FFB703',
        primaryLight: lightenColor('#1F7A8C', 30),
        accentLight: lightenColor('#FFB703', 30),
        primaryRgb: hexToRgb('#1F7A8C'),
        accentRgb: hexToRgb('#FFB703'),
    },
    font: { headline: "'Domine', serif", body: "'Open Sans', sans-serif" },
    background: 'linear-gradient(to right, #A1C4FD, #C2E9FB)',
    designs: genericDesigns,
  },
  {
    id: 'gradient-5',
    name: 'Soft Peach',
    theme: 'light',
    category: 'gradient',
    colors: {
        background: '#FF9A9E', 
        cardBackground: 'rgba(255, 255, 255, 0.8)',
        cardBorder: 'rgba(255, 255, 255, 0.5)',
        cardShadow: 'rgba(250, 208, 196, 0.4)',
        text: '#22223B', 
        heading: '#4A4E69', 
        primary: '#9A8C98', 
        accent: '#C9ADA7',
        primaryLight: lightenColor('#9A8C98', 30),
        accentLight: lightenColor('#C9ADA7', 30),
        primaryRgb: hexToRgb('#9A8C98'),
        accentRgb: hexToRgb('#C9ADA7'),
    },
    font: { headline: "'Orbitron', sans-serif", body: "'Titillium Web', sans-serif" },
    background: 'linear-gradient(to right, #FF9A9E, #FAD0C4)',
    designs: genericDesigns,
  },
  {
    id: 'gradient-6',
    name: 'Deep Sea',
    theme: 'dark',
    category: 'gradient',
    colors: {
        background: '#00C6FF', 
        cardBackground: 'rgba(0, 0, 0, 0.2)',
        cardBorder: 'rgba(255, 255, 255, 0.2)',
        cardShadow: 'rgba(0, 0, 0, 0.3)',
        text: '#FFFFFF', 
        heading: '#B3CDE0', 
        primary: '#FFB400', 
        accent: '#FFFFFF',
        primaryLight: lightenColor('#FFB400', 30),
        accentLight: '#FFFFFF',
        primaryRgb: hexToRgb('#FFB400'),
        accentRgb: hexToRgb('#FFFFFF'),
    },
    font: { headline: "'Poppins', sans-serif", body: "'Nunito Sans', sans-serif" },
    background: 'linear-gradient(to right, #00C6FF, #0072FF)',
    designs: genericDesigns,
  },
  {
    id: 'gradient-7',
    name: 'Golden Hour',
    theme: 'dark',
    category: 'gradient',
    colors: {
        background: '#F7971E', 
        cardBackground: 'rgba(0, 0, 0, 0.3)',
        cardBorder: 'rgba(255, 255, 255, 0.2)',
        cardShadow: 'rgba(0, 0, 0, 0.3)',
        text: '#FFFFFF', 
        heading: '#FFEFC1', 
        primary: '#F05454', 
        accent: '#30475E',
        primaryLight: lightenColor('#F05454', 30),
        accentLight: lightenColor('#30475E', 30),
        primaryRgb: hexToRgb('#F05454'),
        accentRgb: hexToRgb('#30475E'),
    },
    font: { headline: "'Oswald', sans-serif", body: "'Roboto Slab', serif" },
    background: 'linear-gradient(to right, #F7971E, #FFD200)',
    designs: genericDesigns,
  },
  {
    id: 'gradient-8',
    name: 'Purple Haze',
    theme: 'dark',
    category: 'gradient',
    colors: {
        background: '#8E2DE2', 
        cardBackground: 'rgba(0, 0, 0, 0.25)',
        cardBorder: 'rgba(255, 255, 255, 0.2)',
        cardShadow: 'rgba(0, 0, 0, 0.4)',
        text: '#F3F4F6', 
        heading: '#C7D2FE', 
        primary: '#6366F1', 
        accent: '#F59E0B',
        primaryLight: lightenColor('#6366F1', 30),
        accentLight: lightenColor('#F59E0B', 30),
        primaryRgb: hexToRgb('#6366F1'),
        accentRgb: hexToRgb('#F59E0B'),
    },
    font: { headline: "'Philosopher', sans-serif", body: "'Jost', sans-serif" },
    background: 'linear-gradient(to right, #8E2DE2, #4A00E0)',
    designs: genericDesigns,
  },
  {
    id: 'gradient-9',
    name: 'Hot Pink',
    theme: 'dark',
    category: 'gradient',
    colors: {
        background: '#FF6A00', 
        cardBackground: 'rgba(0, 0, 0, 0.3)',
        cardBorder: 'rgba(255, 255, 255, 0.25)',
        cardShadow: 'rgba(0, 0, 0, 0.4)',
        text: '#FFFFFF', 
        heading: '#FFD6E0', 
        primary: '#FFD300', 
        accent: '#4B0082',
        primaryLight: lightenColor('#FFD300', 30),
        accentLight: lightenColor('#4B0082', 30),
        primaryRgb: hexToRgb('#FFD300'),
        accentRgb: hexToRgb('#4B0082'),
    },
    font: { headline: "'Bungee', cursive", body: "'Electrolize', sans-serif" },
    background: 'linear-gradient(to right, #FF6A00, #EE0979)',
    designs: genericDesigns,
  },
  {
    id: 'gradient-10',
    name: 'Green Field',
    theme: 'light',
    category: 'gradient',
    colors: {
        background: '#00F260', 
        cardBackground: 'rgba(255, 255, 255, 0.7)',
        cardBorder: 'rgba(255, 255, 255, 0.4)',
        cardShadow: 'rgba(5, 117, 230, 0.2)',
        text: '#002B4D', 
        heading: '#004E92', 
        primary: '#004E92', 
        accent: '#FFB703',
        primaryLight: lightenColor('#004E92', 30),
        accentLight: lightenColor('#FFB703', 30),
        primaryRgb: hexToRgb('#004E92'),
        accentRgb: hexToRgb('#FFB703'),
    },
    font: { headline: "'Cormorant Garamond', serif", body: "'Proza Libre', sans-serif" },
    background: 'linear-gradient(to right, #00F260, #0575E6)',
    designs: genericDesigns,
  },
  {
    id: 'gradient-11',
    name: 'Blue Power',
    theme: 'dark',
    category: 'gradient',
    colors: {
        background: '#6A11CB', 
        cardBackground: 'rgba(0, 0, 0, 0.2)',
        cardBorder: 'rgba(255, 255, 255, 0.2)',
        cardShadow: 'rgba(0, 0, 0, 0.4)',
        text: '#E0E7FF', 
        heading: '#A5B4FC', 
        primary: '#F59E0B', 
        accent: '#1E3A8A',
        primaryLight: lightenColor('#F59E0B', 30),
        accentLight: lightenColor('#1E3A8A', 30),
        primaryRgb: hexToRgb('#F59E0B'),
        accentRgb: hexToRgb('#1E3A8A'),
    },
    font: { headline: "'Fjalla One', sans-serif", body: "'Nunito', sans-serif" },
    background: 'linear-gradient(to right, #6A11CB, #2575FC)',
    designs: genericDesigns,
  },
  {
    id: 'gradient-12',
    name: 'Warm Sunset',
    theme: 'light',
    category: 'gradient',
    colors: {
        background: '#FCE38A', 
        cardBackground: 'rgba(255, 255, 255, 0.85)',
        cardBorder: 'rgba(255, 255, 255, 0.6)',
        cardShadow: 'rgba(243, 129, 129, 0.25)',
        text: '#2E3A59', 
        heading: '#6B705C', 
        primary: '#D90429', 
        accent: '#3A86FF',
        primaryLight: lightenColor('#D90429', 30),
        accentLight: lightenColor('#3A86FF', 30),
        primaryRgb: hexToRgb('#D90429'),
        accentRgb: hexToRgb('#3A86FF'),
    },
    font: { headline: "'Arvo', serif", body: "'Cabin', sans-serif" },
    background: 'linear-gradient(to right, #FCE38A, #F38181)',
    designs: genericDesigns,
  },
  {
    id: 'gradient-13',
    name: 'Aqua Marine',
    theme: 'light',
    category: 'gradient',
    colors: {
        background: '#36D1DC', 
        cardBackground: 'rgba(255, 255, 255, 0.7)',
        cardBorder: 'rgba(255, 255, 255, 0.4)',
        cardShadow: 'rgba(91, 134, 229, 0.25)',
        text: '#002333', 
        heading: '#0A3B52', 
        primary: '#1B4965', 
        accent: '#F59E0B',
        primaryLight: lightenColor('#1B4965', 30),
        accentLight: lightenColor('#F59E0B', 30),
        primaryRgb: hexToRgb('#1B4965'),
        accentRgb: hexToRgb('#F59E0B'),
    },
    font: { headline: "'Cinzel Decorative', cursive", body: "'Antic Slab', serif" },
    background: 'linear-gradient(to right, #36D1DC, #5B86E5)',
    designs: genericDesigns,
  },
  {
    id: 'gradient-14',
    name: 'Red Passion',
    theme: 'dark',
    category: 'gradient',
    colors: {
        background: '#FF512F', 
        cardBackground: 'rgba(0, 0, 0, 0.3)',
        cardBorder: 'rgba(255, 255, 255, 0.25)',
        cardShadow: 'rgba(0, 0, 0, 0.4)',
        text: '#FFFFFF', 
        heading: '#FFD6E0', 
        primary: '#FFC300', 
        accent: '#4B0082',
        primaryLight: lightenColor('#FFC300', 30),
        accentLight: lightenColor('#4B0082', 30),
        primaryRgb: hexToRgb('#FFC300'),
        accentRgb: hexToRgb('#4B0082'),
    },
    font: { headline: "'Quattrocento', serif", body: "'Quattrocento Sans', sans-serif" },
    background: 'linear-gradient(to right, #FF512F, #DD2476)',
    designs: genericDesigns,
  },
  {
    id: 'gradient-15',
    name: 'Lime Punch',
    theme: 'light',
    category: 'gradient',
    colors: {
        background: '#11998E', 
        cardBackground: 'rgba(255, 255, 255, 0.75)',
        cardBorder: 'rgba(255, 255, 255, 0.5)',
        cardShadow: 'rgba(56, 239, 125, 0.2)',
        text: '#022926', 
        heading: '#065F46', 
        primary: '#065F46', 
        accent: '#FF6B35',
        primaryLight: lightenColor('#065F46', 30),
        accentLight: lightenColor('#FF6B35', 30),
        primaryRgb: hexToRgb('#065F46'),
        accentRgb: hexToRgb('#FF6B35'),
    },
    font: { headline: "'Creepster', cursive", body: "'IM Fell English', serif" },
    background: 'linear-gradient(to right, #11998E, #38EF7D)',
    designs: genericDesigns,
  },
  // Pattern Themes
  {
    id: 'pattern-1',
    name: 'Subtle Dots',
    theme: 'light',
    category: 'pattern',
    colors: {
      background: '#F9F9F9',
      cardBackground: '#FFFFFF',
      cardBorder: '#E0E0E0',
      cardShadow: 'rgba(0, 0, 0, 0.1)',
      text: '#333333',
      heading: '#555555',
      primary: '#4285F4',
      accent: '#DB4437',
      primaryLight: lightenColor('#4285F4', 30),
      accentLight: lightenColor('#DB4437', 30),
      primaryRgb: hexToRgb('#4285F4'),
      accentRgb: hexToRgb('#DB4437'),
    },
    font: { headline: "'Roboto', sans-serif", body: "'Roboto', sans-serif" },
    background: 'radial-gradient(circle, #E0E0E0 1px, transparent 1px), radial-gradient(circle, #E0E0E0 1px, transparent 1px)',
    backgroundColor: '#F9F9F9',
    backgroundSize: '10px 10px',
    designs: genericDesigns,
  },
  {
    id: 'pattern-2',
    name: 'Dark Stripes',
    theme: 'dark',
    category: 'pattern',
    colors: {
      background: '#2C2C2C',
      cardBackground: '#3A3A3A',
      cardBorder: '#484848',
      cardShadow: 'rgba(0, 0, 0, 0.3)',
      text: '#FFFFFF',
      heading: '#B3CDE0',
      primary: '#0F9D58',
      accent: '#F4B400',
      primaryLight: lightenColor('#0F9D58', 30),
      accentLight: lightenColor('#F4B400', 30),
      primaryRgb: hexToRgb('#0F9D58'),
      accentRgb: hexToRgb('#F4B400'),
    },
    font: { headline: "'Lato', sans-serif", body: "'Lato', sans-serif" },
    background: 'repeating-linear-gradient(45deg, #333333, #333333 10px, #2C2C2C 10px, #2C2C2C 20px)',
    designs: genericDesigns,
  },
  {
    id: 'pattern-3',
    name: 'Blueprint Grid',
    theme: 'light',
    category: 'pattern',
    colors: {
      background: '#E3F2FD',
      cardBackground: '#FFFFFF',
      cardBorder: '#BBDEFB',
      cardShadow: 'rgba(25, 118, 210, 0.15)',
      text: '#1C3144',
      heading: '#455A64',
      primary: '#1976D2',
      accent: '#FF6F00',
      primaryLight: lightenColor('#1976D2', 30),
      accentLight: lightenColor('#FF6F00', 30),
      primaryRgb: hexToRgb('#1976D2'),
      accentRgb: hexToRgb('#FF6F00'),
    },
    font: { headline: "'Source Code Pro', monospace", body: "'Source Code Pro', monospace" },
    background: 'linear-gradient(#BBDEFB 1px, transparent 1px), linear-gradient(to right, #BBDEFB 1px, transparent 1px)',
    backgroundColor: '#E3F2FD',
    backgroundSize: '20px 20px',
    designs: genericDesigns,
  },
  {
    id: 'pattern-4',
    name: 'Carbon Fiber',
    theme: 'dark',
    category: 'pattern',
    colors: {
      background: '#222222',
      cardBackground: '#2E2E2E',
      cardBorder: '#3A3A3A',
      cardShadow: 'rgba(0, 0, 0, 0.4)',
      text: '#EFEFEF',
      heading: '#BDBDBD',
      primary: '#D32F2F',
      accent: '#536DFE',
      primaryLight: lightenColor('#D32F2F', 30),
      accentLight: lightenColor('#536DFE', 30),
      primaryRgb: hexToRgb('#D32F2F'),
      accentRgb: hexToRgb('#536DFE'),
    },
    font: { headline: "'Exo 2', sans-serif", body: "'Exo 2', sans-serif" },
    background: 'linear-gradient(45deg, #2a2a2a 25%, transparent 25%), linear-gradient(-45deg, #2a2a2a 25%, transparent 25%), linear-gradient(45deg, transparent 75%, #2a2a2a 75%), linear-gradient(-45deg, transparent 75%, #2a2a2a 75%)',
    backgroundSize: '20px 20px',
    backgroundColor: '#222222',
    designs: genericDesigns,
  },
  {
    id: 'pattern-5',
    name: 'Paper Texture',
    theme: 'light',
    category: 'pattern',
    colors: {
      background: '#F5F5DC',
      cardBackground: '#FFFFFF',
      cardBorder: '#EFEFCE',
      cardShadow: 'rgba(93, 64, 55, 0.15)',
      text: '#5D4037',
      heading: '#795548',
      primary: '#4E342E',
      accent: '#BF360C',
      primaryLight: lightenColor('#4E342E', 30),
      accentLight: lightenColor('#BF360C', 30),
      primaryRgb: hexToRgb('#4E342E'),
      accentRgb: hexToRgb('#BF360C'),
    },
    font: { headline: "'Merriweather', serif", body: "'Merriweather', serif" },
    background: 'url(https://www.transparenttextures.com/patterns/paper.png)',
    backgroundColor: '#F5F5DC',
    designs: genericDesigns,
  },
  {
    id: 'pattern-6',
    name: 'Cosmic',
    theme: 'dark',
    category: 'pattern',
    colors: {
      background: '#000000',
      cardBackground: '#1A1A1A',
      cardBorder: '#262626',
      cardShadow: 'rgba(156, 39, 176, 0.2)',
      text: '#FFFFFF',
      heading: '#E0E0E0',
      primary: '#9C27B0',
      accent: '#03A9F4',
      primaryLight: lightenColor('#9C27B0', 30),
      accentLight: lightenColor('#03A9F4', 30),
      primaryRgb: hexToRgb('#9C27B0'),
      accentRgb: hexToRgb('#03A9F4'),
    },
    font: { headline: "'Orbitron', sans-serif", body: "'Titillium Web', sans-serif" },
    background: 'radial-gradient(ellipse at bottom, #1B2735 0%, #090A0F 100%)',
    designs: genericDesigns,
  },
  {
    id: 'pattern-7',
    name: 'Ocean Waves',
    theme: 'light',
    category: 'pattern',
    colors: {
      background: '#E0F7FA',
      cardBackground: '#FFFFFF',
      cardBorder: '#B2EBF2',
      cardShadow: 'rgba(0, 172, 193, 0.15)',
      text: '#006064',
      heading: '#00838F',
      primary: '#00ACC1',
      accent: '#FF9800',
      primaryLight: lightenColor('#00ACC1', 30),
      accentLight: lightenColor('#FF9800', 30),
      primaryRgb: hexToRgb('#00ACC1'),
      accentRgb: hexToRgb('#FF9800'),
    },
    font: { headline: "'Pacifico', cursive", body: "'Raleway', sans-serif" },
    background: 'repeating-linear-gradient(-45deg, #B2EBF2, #B2EBF2 5px, #E0F7FA 5px, #E0F7FA 25px)',
    designs: genericDesigns,
  },
  {
    id: 'pattern-8',
    name: 'Forest Leaves',
    theme: 'light',
    category: 'pattern',
    colors: {
      background: '#F1F8E9',
      cardBackground: '#FFFFFF',
      cardBorder: '#DCEDC8',
      cardShadow: 'rgba(104, 159, 56, 0.15)',
      text: '#33691E',
      heading: '#558B2F',
      primary: '#689F38',
      accent: '#FF5722',
      primaryLight: lightenColor('#689F38', 30),
      accentLight: lightenColor('#FF5722', 30),
      primaryRgb: hexToRgb('#689F38'),
      accentRgb: hexToRgb('#FF5722'),
    },
    font: { headline: "'Playfair Display', serif", body: "'Lato', sans-serif" },
    background: 'url(https://www.transparenttextures.com/patterns/leaves.png)',
    backgroundColor: '#F1F8E9',
    designs: genericDesigns,
  },
  {
    id: 'pattern-9',
    name: 'Circuit Board',
    theme: 'dark',
    category: 'pattern',
    colors: {
      background: '#0D47A1',
      cardBackground: '#1976D2',
      cardBorder: '#2196F3',
      cardShadow: 'rgba(41, 182, 246, 0.2)',
      text: '#E1F5FE',
      heading: '#81D4FA',
      primary: '#29B6F6',
      accent: '#FFC107',
      primaryLight: lightenColor('#29B6F6', 30),
      accentLight: lightenColor('#FFC107', 30),
      primaryRgb: hexToRgb('#29B6F6'),
      accentRgb: hexToRgb('#FFC107'),
    },
    font: { headline: "'VT323', monospace", body: "'VT323', monospace" },
    background: 'url(https://www.transparenttextures.com/patterns/circuit-board.png)',
    backgroundColor: '#0D47A1',
    designs: genericDesigns,
  },
  {
    id: 'pattern-10',
    name: 'Diamond Tiles',
    theme: 'light',
    category: 'pattern',
    colors: {
      background: '#FCE4EC',
      cardBackground: '#FFFFFF',
      cardBorder: '#F8BBD0',
      cardShadow: 'rgba(194, 24, 91, 0.15)',
      text: '#880E4F',
      heading: '#AD1457',
      primary: '#C2185B',
      accent: '#FF9800',
      primaryLight: lightenColor('#C2185B', 30),
      accentLight: lightenColor('#FF9800', 30),
      primaryRgb: hexToRgb('#C2185B'),
      accentRgb: hexToRgb('#FF9800'),
    },
    font: { headline: "'Dancing Script', cursive", body: "'Open Sans', sans-serif" },
    background: 'linear-gradient(45deg, #F8BBD0 25%, transparent 25%), linear-gradient(-45deg, #F8BBD0 25%, transparent 25%), linear-gradient(45deg, transparent 75%, #F8BBD0 75%), linear-gradient(-45deg, transparent 75%, #F8BBD0 75%)',
    backgroundSize: '30px 30px',
    backgroundColor: '#FCE4EC',
    designs: genericDesigns,
  },
  {
    id: 'pattern-11',
    name: 'Hexagon Honeycomb',
    theme: 'light',
    category: 'pattern',
    colors: {
      background: '#FFF8E1',
      cardBackground: '#FFFFFF',
      cardBorder: '#FFECB3',
      cardShadow: 'rgba(255, 160, 0, 0.2)',
      text: '#FF6F00',
      heading: '#FF8F00',
      primary: '#FFA000',
      accent: '#E65100',
      primaryLight: lightenColor('#FFA000', 30),
      accentLight: lightenColor('#E65100', 30),
      primaryRgb: hexToRgb('#FFA000'),
      accentRgb: hexToRgb('#E65100'),
    },
    font: { headline: "'Bebas Neue', cursive", body: "'Nunito', sans-serif" },
    background: 'url(https://www.transparenttextures.com/patterns/hexabump.png)',
    backgroundColor: '#FFF8E1',
    designs: genericDesigns,
  },
  {
    id: 'pattern-12',
    name: 'Moroccan Tiles',
    theme: 'dark',
    category: 'pattern',
    colors: {
      background: '#1A237E',
      cardBackground: '#283593',
      cardBorder: '#303F9F',
      cardShadow: 'rgba(255, 214, 0, 0.15)',
      text: '#E8EAF6',
      heading: '#C5CAE9',
      primary: '#3F51B5',
      accent: '#FFD600',
      primaryLight: lightenColor('#3F51B5', 30),
      accentLight: lightenColor('#FFD600', 30),
      primaryRgb: hexToRgb('#3F51B5'),
      accentRgb: hexToRgb('#FFD600'),
    },
    font: { headline: "'Cinzel', serif", body: "'Raleway', sans-serif" },
    background: 'url(https://www.transparenttextures.com/patterns/tileable-wood-colored.png)',
    backgroundColor: '#1A237E',
    designs: genericDesigns,
  },
  {
    id: 'pattern-13',
    name: 'Rainbow Diagonal',
    theme: 'light',
    category: 'pattern',
    colors: {
      background: '#FFFFFF',
      cardBackground: 'rgba(255, 255, 255, 0.9)',
      cardBorder: 'rgba(255, 255, 255, 0.6)',
      cardShadow: 'rgba(0, 0, 0, 0.1)',
      text: '#263238',
      heading: '#455A64',
      primary: '#00BCD4',
      accent: '#FF4081',
      primaryLight: lightenColor('#00BCD4', 30),
      accentLight: lightenColor('#FF4081', 30),
      primaryRgb: hexToRgb('#00BCD4'),
      accentRgb: hexToRgb('#FF4081'),
    },
    font: { headline: "'Fredoka One', cursive", body: "'Nunito', sans-serif" },
    background: 'repeating-linear-gradient(45deg, #FF9AA220, #FF9AA220 10px, #FFB7B220 10px, #FFDAC120 20px, #E2F0CB20 30px, #B5EAD720 40px, #C7CEEA20 50px)',
    designs: genericDesigns,
  },
  {
    id: 'pattern-14',
    name: 'Geometric Triangles',
    theme: 'dark',
    category: 'pattern',
    colors: {
      background: '#263238',
      cardBackground: '#37474F',
      cardBorder: '#455A64',
      cardShadow: 'rgba(0, 188, 212, 0.15)',
      text: '#B0BEC5',
      heading: '#90A4AE',
      primary: '#00BCD4',
      accent: '#FF9800',
      primaryLight: lightenColor('#00BCD4', 30),
      accentLight: lightenColor('#FF9800', 30),
      primaryRgb: hexToRgb('#00BCD4'),
      accentRgb: hexToRgb('#FF9800'),
    },
    font: { headline: "'Audiowide', cursive", body: "'Exo 2', sans-serif" },
    background: 'url(https://www.transparenttextures.com/patterns/triangles.png)',
    backgroundColor: '#263238',
    designs: genericDesigns,
  },
  {
    id: 'pattern-15',
    name: 'Watercolor Splatter',
    theme: 'light',
    category: 'pattern',
    colors: {
      background: '#F3E5F5',
      cardBackground: '#FFFFFF',
      cardBorder: '#E1BEE7',
      cardShadow: 'rgba(142, 36, 170, 0.15)',
      text: '#4A148C',
      heading: '#6A1B9A',
      primary: '#8E24AA',
      accent: '#FF6D00',
      primaryLight: lightenColor('#8E24AA', 30),
      accentLight: lightenColor('#FF6D00', 30),
      primaryRgb: hexToRgb('#8E24AA'),
      accentRgb: hexToRgb('#FF6D00'),
    },
    font: { headline: "'Dancing Script', cursive", body: "'Lato', sans-serif" },
    background: 'radial-gradient(circle, #CE93D8 1px, transparent 1px), radial-gradient(circle, #BA68C8 1px, transparent 1px), radial-gradient(circle, #AB47BC 1px, transparent 1px)',
    backgroundSize: '20px 20px, 30px 30px, 40px 40px',
    backgroundColor: '#F3E5F5',
    designs: genericDesigns,
  }
];